apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dating-app

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - nats-deployment.yaml
  - gateway-deployment.yaml
  - member-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: dating-app
